#!/bin/bash

# Name: epoch - default to number of seconds passed since start of 'epoch'. 

# Comment: Example script utility showing bash CASE syntax to handle
# simple single command line args

# Author: Rob Thatcher 2012 http://robthatcher.net

VERSION='0.1.1'

#TODO
#
# Add option to decode an epoch date into human readable 
# i.e. 'date --date='@1363210887' to output 'Wed Mar 13 21:41:27 GMT 2013'

# Vars - Vars

# Make it somewhat multiplatform with by setting the $DATE var after setting $OS to be the output from uname -s

OS=`uname -s`

case $OS in
                 SunOS)
			DATE=/usr/bin/date ;;
                 Darwin)
			DATE=/bin/date ;;
                 Linux)
			DATE=/bin/date ;;
                 *)
			echo -e "\nUnable to determine *nix variant, so we bailed out.\n"
			exit 1
esac

# Another CASE which alters output dependent on command line arg $1, the 'pipe' is an OR.

case $1 in
	-h|--help)
		echo -e "\nPossible flags which may be passed are :\n\n\t-v or --version for version check\n\t-h or --help this help\n\t-l or --long for verbose output\n"
		exit 0;;
	-v|--version)
		echo -e "\nEpoch Script Version $VERSION\n" 
		exit 0 ;;
	-l|--long)
		echo -e "\nTime, as seconds since Epoch `$DATE +%s`, OS determined to be $OS\n";;
	*)
		echo -e "`$DATE +%s`"
esac


